name       : chromaprint
version    : 1.4.2
release    : 6
source     :
    - https://github.com/acoustid/chromaprint/releases/download/v1.4.2/chromaprint-1.4.2.tar.gz : 989609a7e841dd75b34ee793bd1d049ce99a8f0d444b3cea39d57c3e5d26b4d4
license    : LGPL-2.1
component  : programming
summary    : Audio source fingerprint extraction library
description: |
    Library that implements a custom algorithm for extracting fingerprints from any audio source
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(libavutil)
    - pkgconfig(taglib)
    - libboost-devel
setup      : |
    %cmake -DBUILD_TOOLS=ON \
           -DFFT_LIB="fftw3" .
build      : |
    %make
install    : |
    %make_install
