name       : chromaprint
version    : 1.4.3
release    : 8
source     :
    - https://github.com/acoustid/chromaprint/archive/v1.4.3.tar.gz : d4ae6596283aad7a015a5b0445012054c634a4b9329ecb23000cd354b40a283b
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Audio source fingerprint extraction library
description: |
    Library that implements a custom algorithm for extracting fingerprints from any audio source
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(libavutil)
    - pkgconfig(taglib)
    - libboost-devel
setup      : |
    %cmake -DBUILD_TOOLS=ON \
           -DFFT_LIB="fftw3" .
build      : |
    %make
install    : |
    %make_install
