name       : chromaprint
version    : 1.1
release    : 2
source     :
    - https://bitbucket.org/acoustid/chromaprint/downloads/chromaprint-1.1.tar.gz : 6b14d7ea4964581b73bd3f8038c8857c01e446421c1ae99cbbf64de26b47cd12
license    : LGPL-2.1
summary    : Audio source fingerprint extraction library
description: |
    Library that implements a custom algorithm for extracting fingerprints from any audio source
builddeps  :
    - pkgconfig(libavcodec)
    - pkgconfig(taglib)
    - libboost-devel
build      : |
    %cmake .
    %make
install    : |
    %make_install
